name: Backend PR CI

on:
  pull_request:
    paths:
      - 'backend/**'
      - '!**.md'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: '~1.14'
      - name: lint
        run: |
          deno lint -c deno.config.json
      - name: check formatting
        run: |
          deno fmt -c deno.config.json --check
      - name: unit test
        run: |
          deno test -c deno.config.json -j --coverage=coverage_profile --no-check
          deno coverage -q --include="^file:.*/src/.*" coverage_profile
